# Generated by Django 4.2 on 2023-04-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('ETH', 'ETH')], default='ETH', max_length=3, verbose_name='Валюта')),
                ('private_key', models.CharField(max_length=500, verbose_name='Приватный ключ')),
                ('public_key', models.CharField(db_index=True, max_length=400, verbose_name='Публичный ключ')),
                ('balance', models.FloatField(default=0.0, verbose_name='Баланс')),
            ],
            options={
                'verbose_name': 'Кошелёк',
                'verbose_name_plural': 'Кошельки',
                'ordering': ['balance'],
            },
        ),
    ]
